var _tmr=_tmr||[];
(function(){function s(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function z(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function U(a,b){var c,d;if(!a)return"";var e=typeof a;if("number"===e||"boolean"===e||"string"===e||a.nodeType||a===a.window)return"";e=[];if("[object Array]"===Object.prototype.toString.call(a)){c=0;for(d=a.length;c<d;c++)ra(e,null,a[c],b);c="[";d="]"}else{for(c in a)a.hasOwnProperty(c)&&ra(e,
c,a[c],b);c="{";d="}"}return!e.length?"":c+e.join(",")+d}function ra(a,b,c,d){var e=typeof c;if("string"===e)c='"'+c.replace(/[\"\']/g,"\\$&")+'"';else if(!("number"===e||"boolean"===e))if(c=d?"":U(c),!c.length)return;a.push((null===b?"":'"'+b+'":')+c)}function sa(a){var b="";try{var c=new Uint8Array(a);window.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(e){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function t(){return(new Date).getTime()}
function n(a,b){var c={data:b,raw:a,url:"https://top-fwz1.mail.ru"+a},d;"function"!==typeof v.sendBeacon?d=!1:(c.dataSplitter=";",d=V(c.data,c.dataSplitter),d=!0===v.sendBeacon(c.url,d));d||(void 0===b?(c.dataSplitter=";",c.open=Ra,c.connect=Sa,c.startListen=Ta,c.stopListen=Ua,c.open(c),c.connect(c)):("function"===typeof f.XMLHttpRequest?(c.dataSplitter=";",c.open=Va,c.connect=Wa,c.startListen=Xa,c.stopListen=Ya,c.open(c),c.connect(c),d=!0):d=!1,d||Za(c)))}function Za(a){var b=g.createElement("iframe"),
c=g.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);g.body.appendChild(c);try{var d=b.contentWindow.document,e=d.createElement("div"),p;for(p in a.data)if(a.data.hasOwnProperty(p)){var w=a.data[p],L=typeof w;if("string"===L||"number"===L){var q=d.createElement("input");q.setAttribute("type","hidden");q.setAttribute("name",p);q.value=w;e.appendChild(q)}}var f=
d.createElement("form");f.setAttribute("action",a.url);f.setAttribute("method",ta);f.setAttribute("enctype",ua);f.appendChild(e);var h=d.createElement("div");h.appendChild(f);d.body.appendChild(h);var F=function(){try{z(b,"load",F),g.body.removeChild(c)}catch(a){k&&console.warn("[TopMailRu] Error#1.2",a)}};s(b,"load",F);f.submit()}catch(G){k&&console.warn("[TopMailRu] Error#1.3",G)}}function Va(a){a._connection=new f.XMLHttpRequest}function Wa(a){a._connection.open(ta,a.url);a._connection.setRequestHeader("Content-Type",
ua);a._connection.send(V(a.data,a.dataSplitter))}function Xa(a){s(a._connection,"load",a._onload);s(a._connection,"error",a._onerror)}function Ya(a){z(a._connection,"load",a._onload);z(a._connection,"error",a._onerror)}function Ra(a){a._connection=new Image}function Sa(a){a._connection.src=a.url+V(a.data,a.dataSplitter)}function Ta(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function Ua(a){a._connection.onload=null;a._connection.onerror=null}function V(a,b){var c=b||";",d="",
e;for(e in a)if(a.hasOwnProperty(e)){var p=a[e],w=typeof p;if("string"===w||"number"===w)d+=c+escape(e)+"="+escape(p)}return d}function fa(a){return(a=g.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function M(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var e in c)if((b=c[e])||
0===b)a+="; "+e,!0!==b&&(a+="="+b);g.cookie=a}function $a(){var a="tmr"+(""+Math.random()).slice(2);try{return H=f.localStorage||null,H.setItem(a,a),H.removeItem(a),!0}catch(b){return H=null,k&&console.warn("[TopMailRu] Error#1.4",b),!1}}function ab(){if(!W)return null;for(var a=u.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var e=1;e<=c;e++)b=a[e]+"."+b;var e=""+t(),p={domain:b,path:"/",expires:3E5};try{M("tmr_tcdhn",e,p);var w=fa("tmr_tcdhn"),p=p||{};p.expires=-1;M("tmr_tcdhn",
"",p);if(w===e)return b}catch(f){k&&console.warn("[TopMailRu] Error#1.8",f)}}return null}function X(a,b){W&&M(a,b,va);if(ga)try{H.setItem(a,b)}catch(c){k&&console.warn("[TopMailRu] Error#1.6",c)}}function ha(a){var b;if(!(b=W?fa(a):null)){var c;if(ga)a:{try{c=H.getItem(a);break a}catch(d){k&&console.warn("[TopMailRu] Error#1.5",d)}c=null}else c=null;b=c}return b}function wa(a){var b=";e="+escape("detect");n(x(a,"/tracker",!1,!1)+b)}function xa(a,b){if(a.length){var c=U(b);4096<c.length||n("/datalayer",
{js:"13",id:a[0],e:c,sid:ia,ids:a.join(),ver:ja,_:Math.random()})}}function h(){}function N(a){a&&"object"===typeof a&&(!A&&"id"in a)&&(A=a.id)}function bb(a){return(a=!B?void 0:B[a])&&ka?a-ka:void 0}function ya(){if(B){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=!B?void 0:B[b[c]];if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function O(a){return a&&"object"===typeof a&&("id"in a&&a.id||
A)}function x(a,b,c,d){X(la,++I);var e="id"in a?a.id:A,p="url"in a?a.url:u.href,w="referrer"in a?a.referrer:g.referrer,L="title"in a?a.title:g.title,q;q=ma;null===q&&(q=cb());q=null!==q?q?1:0:null;var h="userid"in a?a.userid:y||0===y?y:void 0,l;l=[];A&&e!==A&&l.push("sec");"dataLayer"in f&&l.push("dl");C&&l.push(["ecom"].concat(C).join("-"));l=l.join(",");var F=f.screen,G;G=(new Date).getTimezoneOffset();var m="";if(f.Intl)try{m=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(n){k&&console.warn("[TopMailRu] Error#1.1",
n)}G=G+"/"+m;a.start=ya();b=b+"?js=13"+(e?";id="+escape(e):"")+(p?";u="+escape(p):"")+(w?";r="+escape(w):"")+(a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==h?";userid="+escape(h):"")+(d&&L?";title="+encodeURIComponent(L):"")+(F?";s="+F.width+"*"+F.height:"")+";vp=";e=d=0;g.documentElement&&(g.documentElement.clientWidth||g.documentElement.clientHeight)?(d=g.documentElement.clientWidth,
e=g.documentElement.clientHeight):"number"==typeof f.innerWidth&&(d=f.innerWidth,e=f.innerHeight);b=b+(""+d+"*"+e)+";touch="+db+";hds="+eb+";flash=";if(null===P)if(P="",v.plugins&&v.plugins["Shockwave Flash"])P=v.plugins["Shockwave Flash"].description.split(" ")[2];else if(f.ActiveXObject)try{var r=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),r=r.GetVariable("$version"),r=r.split(" ")[1].split(",");P=r[0]+"."+r[1]}catch(s){k&&console.warn("[TopMailRu] Error#1.12",s)}r=b+P+";sid="+ia+";ver="+
ja+";tz="+encodeURIComponent(G);if(c){if(!B||!na)c="";else{c=[];c.push(na.type);c.push(na.redirectCount);c.push(ka);for(b=0;b<za.length;b++)c.push(bb(za[b]));c=c.join("/")}c=";nt="+c}else c="";c=r+c+("device"in a?";device="+escape(a.device):"")+";ni=";if(!v||!v.connection)r="";else{r=v.connection;b=[];for(e=0;e<Aa.length;e++){d=r[Aa[e]];if(void 0!==d)switch(d){case !0:d=1;break;case !1:d=0;break;default:d=(""+d).replace(/\//g,"_")}b.push(d)}r=b.join("/")}return c+r+("params"in a?";params="+escape(U(a.params,
!1)):"")+(null!==q?";detect="+q:"")+(W||ga?";lvid="+escape([Q,t(),I,J].join(":")):"")+(l?";opts="+escape(l):"")+("version"in a?";appver="+escape(a.version):"")+";_="+Math.random()}function Ba(a){a=";e="+escape("PVT/"+a);for(var b=0;b<m.length;b++)n(x(m[b],"/tracker",!1,!0)+a)}function fb(){ma=!0;Ca(1);if(!Da&&!R){R=!0;for(var a=0;a<m.length;a++)wa(m[a])}}function gb(){Ca(0);ma=!1}function cb(){var a=fa(Ea);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=t()-b;if(0>
b||b>Fa)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function Ca(a){var b=t();a=[a,b].join("|");M(Ea,a,{path:"/",expires:Fa})}function Y(){g.addEventListener?(z(g,"DOMContentLoaded",Y),_tmr.onready()):g.attachEvent&&"complete"===g.readyState&&(z(g,"readystatechange",Y),_tmr.onready())}function Ga(){z(f,"load",Ga);_tmr.onready();_tmr.onload()}function Z(){z(f,"unload",Z);z(f,"beforeunload",Z);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var f=window,v=navigator,
g=document,u=location,S="string"===typeof u.hostname?u.hostname:"",$=-1!=S.search(/(^|\.)odnoklassniki\.ru$/)||-1!=S.search(/(^|\.)ok\.ru$/),aa=-1!=S.search(/(^|\.)vk\.com$/),hb=-1!=S.search(/(^|\.)lamoda\.ru$/),ib=-1!=S.search(/(^|\.)kommersant\.ru$/),jb="string"===typeof u.search&&-1!=u.search.search(/[?&]rb_clickid=/),k="string"===typeof u.search&&-1!=u.search.search(/[?&]tmr_debug=1(?:&|$)/),Ha=$||aa||hb||ib,kb=!jb,lb=$||aa,mb=$||aa,Ia=$||aa,Da=!1,ta="POST",ua="application/x-www-form-urlencoded",
W=!(0===u.hostname.search(/^(\d+.)+\d+$/g)||-1!==u.hostname.search(/:/g)),H=null,ga=$a(),va={domain:ab(),path:"/",expires:287712E5};(function(){var a;if(a=g.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,e=a.length;d<e;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){b=0;for(d=a.length;b<d;b++)e=a[b][0],c=va||{},c.expires=-1,M(e,"",c)}})();var R=!1,ma=null,Fa=864E5,Ea="tmr_detect",nb=function(){function a(a,c){var d=
g.createElement("div");d.setAttribute("class",String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,109,109,98,108,111,99,107,32,98,45,98,97,110,110,101,114,32,98,45,109,101,100,105,97,45,98,97,110,110,101,114,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,109,101,100,105,117,109,95,114,101,99,116,97,110,103,108,101,95,51,48,48,95,50,53,48,32,112,117,98,95,55,50,56,120,57,48,32,108,101,97,100,101,114,98,111,97,114,
100,95,55,50,56,95,57,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,95,54,48,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,120,54,48,48,32,116,101,120,116,45,97,100,32,116,101,120,116,65,100,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,97,100,95,116,101,120,116,32,97,100,95,116,101,120,116,32,98,97,110,110,101,114,95,116,101,120,116,32,
116,101,120,116,45,98,97,110,110,101,114,32,98,45,114,98,32,114,98,45,115,108,111,116,32,98,45,112,114,111,109,111,45,97,100,32,105,45,98,114,97,110,100,105,110,103,32,98,114,97,110,100,105,110,103,45,112,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,98,45,109,105,109,105,99,45,97,100,118,32,112,109,45,116,111,111,108,98,97,114,95,95,98,97,110,110,101,114,32,114,98,95,98,111,100,121,32,115,116,105,99,107,121,45,115,112,114,105,110,103,115,32,97,100,118,95,115,108,111,116,95,49,32,
98,97,110,110,101,114,95,50,52,48,32,98,108,111,99,107,95,115,104,97,114,101,32,97,99,116,105,111,110,45,45,115,104,97,114,101,32,115,104,97,114,101,108,105,115,116,32,106,115,45,98,97,110,110,101,114,32,100,105,114,101,99,116,32,112,99,45,109,105,109,105,99,32,116,103,98,45,98,97,110,110,101,114,32,121,97,100,105,114,101,99,116,32,106,115,45,112,114,111,109,111,45,112,111,112,117,112,32,109,45,115,117,98,115,99,114,105,112,116,105,111,110,32,112,45,116,97,114,103,101,116,32,112,45,100,105,114,101,
99,116,104,97,99,107,32,114,98,45,102,108,111,97,116,105,110,103,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107));d.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");d.setAttribute("id","trg-b-banners-1");d.setAttribute("data-view","SlotView.mimic");this.bait=g.body.appendChild(d);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;
this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=a||null;this.fnNegative=c||null;var e=this;setTimeout(function(){e._checkBait.call(e)},1)}a.prototype._checkBait=function(){if(R)this._stop();else{var a=!1;null!==g.body.getAttribute("abp")||null===this.bait.offsetParent||0==this.bait.offsetHeight||0==this.bait.offsetLeft||0==this.bait.offsetTop||0==this.bait.offsetWidth||0==this.bait.clientHeight||0==this.bait.clientWidth?a=!0:void 0!==f.getComputedStyle&&(a=f.getComputedStyle(this.bait,
null),a="none"==a.getPropertyValue("display")||"hidden"==a.getPropertyValue("visibility"));(!0===a||10<=++this.loopNumber)&&this._stop();var c;if(a&&this.fnPositive)try{c=this.fnPositive,c()}catch(d){k&&console.warn("[TopMailRu] Error#1.9",d)}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}else try{c=this.fnNegative,c()}catch(p){k&&console.warn("[TopMailRu] Error#1.10",p)}}};a.prototype._stop=function(){try{g.body.removeChild(this.bait)}catch(a){k&&
console.warn("[TopMailRu] Error#1.11",a)}};return function(b,c){new a(b,c)}}(),C=null,Ja=!1,oa=[],Ka;(function(){function a(a){for(var b=[],f,g,h=0,l=a.length;h<l;h++)if(g=a[h]){f=null;if(g.ecommerce){g=g.ecommerce;f=!1;var k={},m=void 0;for(m in g)g.hasOwnProperty(m)&&c[m]&&(f=!0,k[m]=g[m]);f=f?k:null}else if("event"===g[0])if(k=d[g[1]],g=g[2],!k||!g.items)f=null;else{f={};f[k]={products:g.items};var k=!1,m={},n=void 0;for(n in g)"items"!==n&&("currency"===n?f.currencyCode=g[n]:e[n]?(k=!0,m[e[n]]=
g[n]):g[n]&&(k=!0,m[n]=g[n]));k&&(f.actionField=m)}f&&(b.push(f),oa.push(f))}if(b.length){a=0;for(h=b.length;a<h;a++)xa(La,b[a]);C||(C=[0,0]);C[0]+=b.length;h=a=0;for(l=b.length;h<l;h++)a+=U(b[h]).length;C[1]+=a}}function b(b){if((b=f[b])&&"function"===typeof b.push){a(b);var c=b.push;b.push=function(){var b=c.apply(this,arguments);a([].slice.call(arguments,0));return b}}}var c={currencyCode:"currencyCode",detail:"detail",add:"add",remove:"remove",checkout:"checkout",purchase:"purchase",refund:"refund"},
d={view_item:c.detail,add_to_cart:c.add,remove_from_cart:c.remove,begin_checkout:c.checkout,purchase:c.purchase,refund:c.refund},e={transaction_id:"id",value:"revenue"};Ka=function(){b("dataLayer");Ja=!0}})();var ja="60.3.0",pa=0,ba=0,ia=sa(16),y=null,ca=0,la="tmr_reqNum",I=ha(la),I=null===I?0:parseInt(I,10);X(la,I);var J=ha("tmr_lvid"),Q=ha("tmr_lvidTS");if(null===J||-1===J.search(/^[0-9a-fA-F]+$/))J=sa(32);X("tmr_lvid",J);if(null===Q||-1===Q.search(/^\d+$/))Q=""+t();X("tmr_lvidTS",Q);var A=0,m=
[],da=[],ea=[],La=[],db="ontouchstart"in f||1<(v.maxTouchPoints||v.msMaxTouchPoints)?"1":"0",eb=f.devicePixelRatio||0,P=null,Ma=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},B=Ma.timing||{},na=Ma.navigation||{},za="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
ka=!B?void 0:B.navigationStart,Aa="downlink downlinkMax effectiveType rtt saveData type".split(" "),D,qa;D=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||A,e=c.title||null,g,f=qa(b,{params:c.required,fn:c.fn});if(f.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<f.missed.length&&f.missed.slice(0,-1).join(", ")+" and "||"")+f.missed.slice(-1)+" in "+a);else{var h=qa(b,{params:c.optional,fn:c.fn});g=[].concat(f.values).concat(h.values);f=[].concat(f.missed).concat(h.missed);
c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?g.push("value: "+b):f.push("value"));c=g.length?"{ "+g.join(", ")+" }":"";g=f.length?"("+(1<f.length?f.slice(0,-1).join(", ")+" and "+f.slice(-1)+" are":f.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+c+" "+g):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};qa=function(a,b){var c=[],d=[],e,f,g;if(b.params)for(e in b.params)if(b.params.hasOwnProperty(e)&&
!1!==b.params[e])if(f=e in a&&a[e],!0!==b.params[e]&&(f=f||b.params[e]),f)try{g=b.fn?b.fn:null,c.push(e+': "'+(g?g(e,f):f)+'"')}catch(h){console.warn("[TopMailRu] Error#1.16",h)}else d&&d.push(e);return{values:c,missed:d}};h.prototype.callbackOnReady=function(a){k&&D("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&a.callback.call(a.context||null)};h.prototype.pageView=function(a){N(a);var b;if(b=a&&"object"===typeof a&&"id"in a)if(b=a.id)if(b=5>da.length){b:{for(b=
0;b<da.length;b++)if(da[b]===a.id){b=!0;break b}b=!1}b=!b}if(b){da.push(a.id);!1!==a.beat&&ea.push(a.id);if(!0===a.ecom&&(La.push(a.id),b=[a.id],Ja))for(var c=0,d=oa.length;c<d;c++)xa(b,oa[c]);m.push(a);R&&wa(a)}k&&D("pageView",a,{title:"Page view",optional:{url:u.href}});O(a)&&(n(x(a,"/counter",!1,!0)),ba=t())};h.prototype.reachGoal=function(a){N(a);k&&D("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(O(a)&&"goal"in a&&a.goal){var b="";"value"in a&&a.value&&(b=parseInt(a.value)||
"");n(x(a,"/tracker",!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};h.prototype.itemView=function(a){k&&D("itemView",a,{title:"Item view",optional:{list:!0,productid:!0,pagetype:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(O(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0;(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||A)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();b="IV:"+e+"/"+(""+b).replace(/;/g,
" ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");n(x(a,"/tracker",!1,!1)+(";e="+escape(b)))}};h.prototype.sendEvent=function(a){N(a);k&&D("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substr(0,300).replace(/;/g," ")}});if(O(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substr(0,300),c=(""+a.action).substr(0,300),d="";"label"in a&&a.label&&(d=(""+a.label).substr(0,300));var e=
"";"value"in a&&a.value&&(e=parseInt(a.value)||"");b="CE:"+e+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");n(x(a,"/tracker",!1,!1)+(";e="+escape(b)))}};h.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?k&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(y=a,k&&console.info("[TopMailRu]: Global user ID = "+y))}};h.prototype.getUserID=function(){return y||
0===y?y:void 0};h.prototype.deleteUserID=function(){y=null;k&&console.info("[TopMailRu]: Reset global user ID to null")};h.prototype.getClientID=function(){var a=J;return a||0===a?a:void 0};h.prototype._MT_event=function(a,b,c){N(a);k&&D(b,a,{title:c});O(a)&&n(x(a,"/tracker",!1,!0)+(";e="+escape("MT:/"+b)))};h.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};h.prototype.processEvent=function(a,b){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(b&&
0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "miniAppEvent":this.miniAppEvent(a)}}else k&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else k&&console.warn("[TopMailRu] Error#1.18",
"Invalid push event")};h.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var Na=!1;h.prototype.onready=function(){Na||(Na=!0,!Da&&!R&&nb(fb,gb),Ka())};var Oa=!1;h.prototype.onload=function(){if(!Oa){Oa=!0;ca=t();if(!mb&&0<m.length){for(var a=";e="+escape("RT/load")+";et="+ca,b=0;b<m.length;b++)n(x(m[b],"/tracker",!0,!1)+a);ba=ca}kb||setTimeout(function(){Ba(2)},2E3);lb||setTimeout(function(){Ba(15)},15E3)}};h.prototype.beat=function(){if(!Ha&&pa){var a=
t();if(!(12E4<a-pa)){if(12E4<a-ba)for(var b=";e="+escape("RT/resend")+";et="+ca,c=0;c<m.length;c++)!1!==m[c].beat&&n(x(m[c],"/tracker",!1,!0)+b);else 0<ea.length&&n("/tracker?"+V({js:"13",id:ea[0],e:"RT/beat",sid:ia,ids:ea.join(),ver:ja,_:Math.random()},";"));ba=a}}};var Pa=!1;h.prototype.unload=function(){if(!Pa&&(Pa=!0,!Ia)){var a;a=(a=ya())?t()-a:void 0;a=";e="+escape("RT/unload")+";et="+t()+(a?";pvt="+escape(a):"");for(var b=0;b<m.length;b++)n(x(m[b],"/tracker",!1,!1)+a)}};h.prototype.activity=
function(a){pa=t()};var K=_tmr;_tmr=new h;for(var l=0,T=K.length,E;l<T;l++)(E=K[l])&&"object"===typeof E&&N(E);l=0;for(T=K.length;l<T;l++)E=K[l],_tmr.processEvent(E,1);l=0;for(T=K.length;l<T;l++)E=K[l],_tmr.processEvent(E,-1);if("complete"===g.readyState||"loading"!==g.readyState&&!g.documentElement.doScroll)_tmr.onready();else g.addEventListener?s(g,"DOMContentLoaded",Y):g.attachEvent&&s(g,"readystatechange",Y);if("complete"===g.readyState)_tmr.onload();else s(f,"load",Ga);Ia||(s(f,"unload",Z),s(f,
"beforeunload",Z));if(!Ha){setInterval(function(){_tmr.beat()},6E4);try{for(var Qa="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),ob=function(a){s(g,a,function(){_tmr.activity(a)})},l=0;l<Qa.length;l++)ob(Qa[l]);s(f,"scroll",function(){_tmr.activity("scallback")})}catch(pb){k&&console.warn("[TopMailRu] Error#1.20",pb)}}}})();
